POST http://localhost:8080/login
Content-Type: application/json

{
    "user_name":"sujith1",
    "password":"password"

}

###

POST http://localhost:8080/register
Content-Type: application/json

{
    "user_name":"sujith13",
    "password":"password",
    "email":"123@gmail.com"


}

###

GET http://localhost:8080/claims/f611a1a2-ad7e-4ce8-aae2-bf0a992d0e46

###

GET http://localhost:8080/insurer/claims?

###

POST http://localhost:8080/logout


###

GET http://localhost:8080/claims?